title: Haal kleuren uit een afbeelding
hero_image: images/banner.png
description: Haal kleuren uit een afbeelding.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Haal kleuren uit een afbeelding
