title: Get colours from an image
hero_image: images/banner.png
description: Get colours from an image
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Get colours from an image
