title: Obtener colores de una imagen
hero_image: images/banner.png
description: Obtener colores de una imagen.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Obtener colores de una imagen
