title: Obtenir les couleurs d'une image
hero_image: images/banner.png
description: Obtiens les couleurs d'une image.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Obtenir les couleurs d'une image
